spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://luozuishuai.mysql.rds.aliyuncs.com:3306/business
    username: root
    password: Lgb58642626
mybatis:
  mapper-locations: classpath:mapper/*.xml