spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/business
    username: root
    password: rootroot
  mail:
    host: smtp.126.com
    username: root
    password: root
  task:
    execution:
      pool:
        core-size: 50
mybatis:
  mapper-locations: classpath:mapper/*.xml
server:
  port: 9090